### *26/02/2026*

In [9]:
import numpy as np
array=np.array([1,2,3,4])
print(array)
print(type(array))
print(array*2)

[1 2 3 4]
<class 'numpy.ndarray'>
[2 4 6 8]


In [4]:
import numpy as np

zeros1 = np.zeros(3)
print(zeros1)

zeros = np.zeros((2, 3))
print(zeros)

ones = np.ones((3, 3))
print(ones)

[0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [5]:
import numpy as np

arr = np.array([[1, 2],[3, 4]])
print(arr.size)

arr1 = np.array([[1, 2, 3],[2, 3, 4],[4, 5, 5],[6, 7, 6]])
print(arr1.size)
print(arr1)
print(arr)
print(type(arr))

4
12
[[1 2 3]
 [2 3 4]
 [4 5 5]
 [6 7 6]]
[[1 2]
 [3 4]]
<class 'numpy.ndarray'>


In [6]:
import numpy as np

a = np.arange(1, 7)
print(a)

b = a.reshape(3, 2)
print(b)

[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]


In [7]:
import numpy as np

arr = np.array([[1,2],[3,4],[5,6]])

print(arr[-1])      
print(arr[1][0])    

arr1 = np.array([[[1,2],[2,3]],[[3,4],[3,5]]])

print(arr1[0])   

[5 6]
3
[[1 2]
 [2 3]]
