### *26/02/2026*

In [9]:
import numpy as np
array=np.array([1,2,3,4])
print(array)
print(type(array))
print(array*2)

[1 2 3 4]
<class 'numpy.ndarray'>
[2 4 6 8]


In [4]:
import numpy as np

zeros1 = np.zeros(3)
print(zeros1)

zeros = np.zeros((2, 3))
print(zeros)

ones = np.ones((3, 3))
print(ones)

[0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [5]:
import numpy as np

arr = np.array([[1, 2],[3, 4]])
print(arr.size)

arr1 = np.array([[1, 2, 3],[2, 3, 4],[4, 5, 5],[6, 7, 6]])
print(arr1.size)
print(arr1)
print(arr)
print(type(arr))

4
12
[[1 2 3]
 [2 3 4]
 [4 5 5]
 [6 7 6]]
[[1 2]
 [3 4]]
<class 'numpy.ndarray'>


In [6]:
import numpy as np

a = np.arange(1, 7)
print(a)

b = a.reshape(3, 2)
print(b)

[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]


In [7]:
import numpy as np

arr = np.array([[1,2],[3,4],[5,6]])

print(arr[-1])      
print(arr[1][0])    

arr1 = np.array([[[1,2],[2,3]],[[3,4],[3,5]]])

print(arr1[0])   

[5 6]
3
[[1 2]
 [2 3]]


### *27/02/2026*

In [16]:
import numpy as np

a = np.array([1, 2, 3, 4])
b = np.array([4, 5, 6, 7])

print(a / b)
print(a + 10)
print(a * 3)
print(np.sum(a))
print(np.max(a))

[0.25       0.4        0.5        0.57142857]
[11 12 13 14]
[ 3  6  9 12]
10
4


In [14]:
import numpy as np

a = np.array([1, 2, 3, 4])
b = np.array([4, 5, 6, 7])

print(np.std(a))
print(np.std(b))

1.118033988749895
1.118033988749895


In [15]:
import numpy as np

a = np.array([[1, 2, 5],
              [3, 4, 6],
              [3, 4, 5]])

print(np.linalg.norm(a))

11.874342087037917


In [17]:
import numpy as np

b = np.array([[1, 2],
              [3, 4]])

a = np.array([[5, 6],
              [1, 2]])

print(a @ b)

[[23 34]
 [ 7 10]]


In [18]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])   

b = np.array([10, 20, 30])   

print(arr + b)

[[11 22 33]
 [14 25 36]]


In [19]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([3, 4, 5])

print(np.dot(a, b))

26


In [21]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# axis=0  column-wise
# axis=1  row-wise

print(np.sum(arr, axis=0))
print(np.sum(arr, axis=1))

[5 7 9]
[ 6 15]


In [22]:
import numpy as np

a = np.array([[1, 2],
              [3, 4],
              [5, 6]])

print(a.T)

[[1 3 5]
 [2 4 6]]


In [23]:
import numpy as np

a = np.array([1, 2, 3, 4])
b = np.array([4, 5, 6, 7])

print(np.mean(a))
print(np.mean(b))

2.5
5.5


In [24]:
import numpy as np

a = np.array([[1, 2, 5],
              [3, 4, 6],
              [3, 4, 5]])

print(np.linalg.det(a))
print(np.linalg.inv(a))

2.0000000000000004
[[-2.   5.  -4. ]
 [ 1.5 -5.   4.5]
 [-0.   1.  -1. ]]
